//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamDataModel
{
    using HamDataTransactions;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;

    public partial class GolfJugada
    {
        #region Propiedades
        public int JugadasId { get; set; }
        public int CompetidorJornadaId { get; set; }
        public int HoyoParId { get; set; }
        public int Golpes { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioId { get; set; }

        const string Entity = "GolfJugadas";
        public static string toOrder = "Score";
        #endregion

        #region Metodos DML
        public bool Insert()
        {
            DBTransaction db = new DBTransaction();
            List<SqlParameter> ps = new List<SqlParameter>();
            ps = SetParameters(ps);
            db.ExecStoreProcedure("[golf].[pRegistrarGolpes]", ps);
            return (db.RowAffected > 0);
        }

        public static bool DeletePuntaje(int competidorJornadaId)
        {
            DBTransaction db = new DBTransaction();
            List<SqlParameter> ps = new List<SqlParameter>();
            ps.Add(new SqlParameter("CompetidorJornadaId", competidorJornadaId));
            db.ExecStoreProcedure("[golf].[pDeleteJugadas]", ps);
            return (db.RowAffected > 0);
        }
        #endregion

        #region Metodos Get
        public static DataTable TotalesTorneo(int eventoId, int categoriaId)
        {
            DataTable dtJornadas = GolfJornada.GetNroJornadas(eventoId);
            DataTable dt = GetAllTotales(dtJornadas, categoriaId);
            dt = CalcularScores(dt, dtJornadas);
            dt.DefaultView.Sort = toOrder + " ASC";
            dt = SetPosicionTabla(dt.DefaultView.ToTable());
            return dt;
        }

        public static GolfJugada GetJugada(int jugadasId)
        {
            return Parse(jugadasId);
        }

        public static DataTable GetTotalesFinales(int jornada, int categoria)
        {
            DBTransaction db = new DBTransaction();
            DataTable dt = db.GetDataView(string.Format("[golf].[vTotalJornada] where jornadaId = {0} and CategoriaId = {1} order by CompetidorId asc", jornada, categoria));
            //dbTools.Sql = string.Format("select [CompetidorId],[Nombre],[Handicap(80%)],[1RA],[2DA],[Gross],[Neto] from [vGolfTotalJornada] where [Neto] is not null and jornadaId = {0} and CategoriaId = {1} order by CompetidorId asc", jornada, categoria);
            return dt;
        }

        public static DataTable GetTotalesFinalesReporte(int jornada, int categoria)
        {
            DBTransaction db = new DBTransaction();
            DataTable dt = db.GetDataView(string.Format("[vGolfTotalJornada] where [Neto] is not null and jornadaId = {0} and CategoriaId = {1} order by CompetidorId asc", jornada, categoria));
            //dbTools.Sql = string.Format("select [CompetidorId],[Nombres],[Handicap(80%)],[1RA],[2DA],[Gross],[Neto] from [vGolfTotalJornada] where [Neto] is not null and jornadaId = {0} and CategoriaId = {1} order by CompetidorId asc", jornada, categoria);
            return dt;
        }

        public static DataTable GetTarijeta(int competidorJornadaId1, int competidorJornadaId2, int competidorJornadaId3, int competidorJornadaId4)
        {
            DBTransaction db = new DBTransaction();
            List<SqlParameter> ps = new List<SqlParameter>();
            ps.Add(new SqlParameter("CompetidorJornadaId1", competidorJornadaId1));
            ps.Add(new SqlParameter("CompetidorJornadaId2", competidorJornadaId2));
            ps.Add(new SqlParameter("CompetidorJornadaId3", competidorJornadaId3));
            ps.Add(new SqlParameter("CompetidorJornadaId4", competidorJornadaId4));
            return db.GetStoreProcedure("[golf].[pGetTarjetaCompetidores]", ps);
        }

        public static DataTable GetGolpes(int competidorJornadaId, int hoyoParId)
        {
            DBTransaction db = new DBTransaction();
            return db.GetDataView(string.Format("[golfJugadas] WHERE [CompetidorJornadaId] = {0} and [HoyoParId] = {1}", competidorJornadaId, hoyoParId));
            //dbTools.Sql = string.Format("SELECT [Golpes] FROM [golfJugadas] WHERE [CompetidorJornadaId] = {0} and [HoyoParId] = {1}", competidorJornadaId, hoyoParId);
        }

        public static DataTable GetTotales(int grupoId)
        {
            DBTransaction db = new DBTransaction();
            List<SqlParameter> ps = new List<SqlParameter>();
            ps.Add(new SqlParameter("grupoId", grupoId));
            return db.GetStoreProcedure("golf.pCalcularNeto", ps);
        }
        #endregion

        #region Private Members
        private static GolfJugada Parse(int jugadasId)
        {
            DBTransaction db = new DBTransaction();
            Dictionary<string, int> fields = new Dictionary<string, int>();
            fields.Add(nameof(JugadasId), jugadasId);
            DataRow dr = db.GetDataRow(Entity, fields);
            GolfJugada cg = ConvertToCategoia(dr);
            return cg;
        }

        private static GolfJugada ConvertToCategoia(DataRow dr)
        {
            GolfJugada gj = new GolfJugada();
            if (dr != null)
            {
                gj.JugadasId = Convert.ToInt32(dr["JugadasId"]);
                gj.CompetidorJornadaId = Convert.ToInt32(dr["CompetidorJornadaId"]);
                gj.HoyoParId = Convert.ToInt32(dr["HoyoParId"]);
                gj.Golpes = Convert.ToInt32(dr["Golpes"]);
                gj.FechaRegistro = Convert.ToDateTime(dr["FechaRegistro"]);
                gj.UsuarioId = Convert.ToInt32(dr["UsuarioId"]);
            }
            return gj;
        }

        private List<SqlParameter> SetParameters(List<SqlParameter> ps)
        {
            ps.Add(new SqlParameter("CompetidorJornadaId", CompetidorJornadaId));
            ps.Add(new SqlParameter("HoyoParId", HoyoParId));
            ps.Add(new SqlParameter("Golpe", Golpes));
            ps.Add(new SqlParameter("UsuarioId", UsuarioId));
            return ps;
        }

        private static DataTable GetAllTotales(DataTable dtJornadas, int cateId)
        {
            DataTable dt = new DataTable();
            DataTable dtauxi = new DataTable();
            int contador = 2;
            int contCol = 7;
            string namecolum = string.Empty;
            int vuno, vdos = 0;
            foreach (DataRow dr in dtJornadas.Rows)
            {
                contCol = 7;
                if (dt.Rows.Count < 1)
                {
                    dtauxi = GetTotalesFinales(Convert.ToInt32(dr[0]), cateId);
                    dt = dtauxi;
                }
                else
                {
                    dtauxi = GetTotalesFinales(Convert.ToInt32(dr[0]), cateId);
                    int nrofilasauxi = dtauxi.Rows.Count;
                    int contadorauxi = 0;
                    int[] nRows = new int[nrofilasauxi];

                    if (dtauxi.Rows.Count > 0)
                    {
                        for (int x = 0; x < dt.Rows.Count; x++)
                        {
                            if (contadorauxi < nrofilasauxi)
                            {
                                vuno = Convert.ToInt32(dt.Rows[x]["CompetidorId"]);
                                vdos = Convert.ToInt32(dtauxi.Rows[contadorauxi]["CompetidorId"]);
                                if (vuno == vdos)
                                {
                                    nRows[contadorauxi] = x;
                                    contadorauxi++;
                                }
                            }
                            else
                            {
                                x = dt.Rows.Count;
                            }
                        }

                        for (int x = 0; x <= 3; x++)
                        {
                            namecolum = dtauxi.Columns[contCol].ColumnName;
                            namecolum = string.Format("{0} {1}", namecolum, contador);
                            dt.Columns.Add(namecolum);
                            for (int i = 0; i < dtauxi.Rows.Count; i++)
                            {
                                dt.Rows[nRows[i]][namecolum] = dtauxi.Rows[i][contCol];
                            }
                            contCol++;
                        }
                    }
                    contador++;
                }
            }
            return dt;
        }

        private static DataTable CalcularScores(DataTable dt, DataTable dtJornadas)
        {
            int nroRow = 0;
            int totalNeto = 0;
            int totalGross = 0;
            int parjornadas = 0;
            if (dt.Columns.Count > (dtJornadas.Rows.Count * 4) + 6)
            {
                parjornadas = GolfHoyoPar.GetParTotal() * dtJornadas.Rows.Count;
                dt.Columns.Add("Total Gross");
                dt.Columns.Add("Total Neto");
                dt.Columns.Add("Score", typeof(Int32));
                foreach (DataRow dr in dt.Rows)
                {
                    totalNeto = 0;
                    totalGross = 0;
                    for (int i = 1; i <= dtJornadas.Rows.Count; i++)
                    {
                        if (totalGross == 0)
                        {
                            totalGross = totalGross + Convert.ToInt32(dr["Gross"]);
                        }
                        else
                        {
                            if (string.IsNullOrEmpty(dr["Gross" + " " + i].ToString()))
                            {
                                totalGross = totalGross + 500;
                            }
                            else
                            {
                                totalGross = totalGross + Convert.ToInt32(dr["Gross" + " " + i]);
                            }
                        }

                        if (totalNeto == 0)
                        {
                            try
                            {
                                totalNeto = totalNeto + Convert.ToInt32(dr["Neto"]);
                            }
                            catch { }
                        }
                        else
                        {
                            if (string.IsNullOrEmpty(dr["Neto" + " " + i].ToString()))
                            {
                                totalNeto = totalNeto + 500;
                            }
                            else
                            {
                                totalNeto = totalNeto + Convert.ToInt32(dr["Neto" + " " + i]);
                            }
                        }
                    }
                    dt.Rows[nroRow]["Total Gross"] = totalGross;
                    dt.Rows[nroRow]["Total Neto"] = totalNeto;
                    dt.Rows[nroRow]["Score"] = totalGross - parjornadas;
                    nroRow++;
                }
            }
            else
            {
                parjornadas = GolfHoyoPar.GetParTotal();
                dt.Columns.Add("Score", typeof(Int32));
                foreach (DataRow dr in dt.Rows)
                {
                    totalGross = Convert.ToInt32(dr["Gross"]);
                    dt.Rows[nroRow]["Score"] = totalGross - parjornadas;
                    nroRow++;
                }
            }
            return dt;
        }

        private static DataTable SetPosicionTabla(DataTable dtTotales)
        {
            dtTotales.Columns.Add("Posición").SetOrdinal(0);
            int position = 1;
            int axuPosition = 1;
            int fila = 0;
            string scoreAnterior = string.Empty;
            foreach (DataRow dr in dtTotales.Rows)
            {
                if (position < 4)
                {
                    dtTotales.Rows[fila]["Posición"] = position;
                    position++;
                }
                else
                {
                    if (scoreAnterior == dtTotales.Rows[fila]["Score"].ToString())
                    {
                        scoreAnterior = dtTotales.Rows[fila]["Score"].ToString();
                        dtTotales.Rows[fila]["Posición"] = string.Format("E{0}", axuPosition);
                        dtTotales.Rows[fila - 1]["Posición"] = string.Format("E{0}", axuPosition);
                    }
                    else
                    {
                        axuPosition = position;
                        scoreAnterior = dtTotales.Rows[fila]["Score"].ToString();
                        dtTotales.Rows[fila]["Posición"] = axuPosition;
                    }
                    position++;
                }
                fila++;
            }
            return dtTotales;
        }


       
        #endregion

    }
}
